#保存为utf-8格式
spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev   #开发环境
  application:
    name: springcloud-config-haoge-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: springcloud-config-haoge-test